version: '3.9'

services:
  db:
    container_name: 'fasters-db'
    build:
      context: ./docker
      dockerfile: Dockerfile-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - "./docker/setup.sql:/docker-entrypoint-initdb.d/1.sql"
      - persistent-db-vol:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5

  manage:
    container_name: 'fasters-manage'
    build:
      context: ./docker
      dockerfile: Dockerfile-manage
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8002:80'
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  persistent-db-vol: